[package]
name = "bk"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "bk"
path = "src/main.rs"

[dependencies]
chrono = "0.4.39"
log = "0.4.27"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.9.0"
yansi = "1.0.1"
