# Run a script before backup
# start_script = "before.sh"

# Run a script after backup
# end_script = "after.sh"

# Rsync Operation
# [[rsync]]
# Directories SHOULD have trailing `/`
# src = "/home/me/"
# dest = "/backup/home/me/"

# Excludes
# exclude = [".cache", ".local"]

# Delete entries not present in `src` from `destination`
# delete = true

# Ensure this directory exists and it not empty before running rsync
# ensure_exists = "/home"

# Make a CephFS snapshot before rsync
# cephfs_snap = true

# Restic Operation
# [[restic]]
# targets = ["my_restic_target"] 
# src = [
#   "my_path"
# ]

# exclude = [
#     "/exclude"
# ]

# exclude_caches = true
# exclude_if_present = [
#     ".nobk"
# ]
# reread = true
# one_file_system = true
# concurrency = 4
# tags = [
#     "tag1"
# ]

# compression = "auto"

# Restic Targets

# [restic_target.my_restic_target]
# repo = "/backup/repo.restic"
# passphrase = "password"

# Path

# [path.my_path]
# path = "/my_path"
# ensure_exists = "/dir"
# cephfs_snap = true
# same_path = true
